export const sampleSongs = {
  happy: [
    {
      id: "1",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "2",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "3",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "4",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "5",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
  sad: [
    {
      id: "6",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "7",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "8",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "9",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "10",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
  energetic: [
    {
      id: "11",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "12",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "13",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "14",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "15",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
  chill: [
    {
      id: "16",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "17",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "18",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "19",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "20",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
  witty: [
    {
      id: "21",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "22",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "23",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "24",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "25",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
  mysterious: [
    {
      id: "26",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "27",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "28",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "29",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
    {
      id: "30",
      title: "placeholder",
      artist: "placeholder",
      spotifyUrl: "placeholder",
      albumCover: "",
    },
  ],
};
